export const ABORT_REQUEST = 'ABORT_REQUEST';

export const AUTHENTICATION = 'AUTHENTICATION';

export const ENABLE_ABORT_REQUEST = 'ENABLE_ABORT_REQUEST';

export const LOADING = 'LOADING';

export const NO_OP = 'NO_OP';

export const RESTORE_FROM_LOCAL_STORAGE = 'RESTORE_FROM_LOCAL_STORAGE';
